// Optimized icon system - only import icons that are actually used
// This reduces bundle size significantly compared to importing from lucide-react directly

// Core icons used throughout the app
export { 
  // Navigation
  Home,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  
  // Actions
  Plus,
  Minus,
  Edit,
  Trash2,
  Copy,
  Download,
  Upload,
  Save,
  Search,
  Filter,
  Settings,
  MoreHorizontal,
  MoreVertical,
  
  // Status
  Check,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  Loader2,
  
  // User & Auth
  User,
  Users,
  UserPlus,
  LogOut,
  LogIn,
  Lock,
  Unlock,
  
  // Content
  FileText,
  File,
  Image,
  Video,
  BookOpen,
  Book,
  MessageSquare,
  MessageCircle,
  Mail,
  Phone,
  Calendar,
  Clock,
  Timer,
  
  // Media
  Play,
  Pause,
  Stop,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  
  // Learning
  GraduationCap,
  Award,
  Trophy,
  Star,
  Target,
  Zap,
  Lightbulb,
  Brain,
  
  // Communication
  Send,
  Reply,
  Share,
  Link,
  ExternalLink,
  
  // Data & Analytics
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  Database,
  
  // System
  Wifi,
  WifiOff,
  Battery,
  BatteryLow,
  Monitor,
  Smartphone,
  Tablet,
  
  // UI Elements
  Eye,
  EyeOff,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Flag,
  Bookmark,
  Tag,
  Tags,
  
  // Forms
  CheckSquare,
  Square,
  Circle,
  Radio,
  ToggleLeft,
  ToggleRight,
  
  // Navigation & Layout
  Grid,
  List,
  Layout,
  Sidebar,
  PanelLeft,
  PanelRight,
  
  // Tools
  Wrench,
  Hammer,
  Scissors,
  Palette,
  Brush,
  Wand2,
  
  // Time & Date
  CalendarDays,
  CalendarCheck,
  CalendarX,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  Clock10,
  Clock11,
  Clock12,
  
  // Weather & Environment
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  Wind,
  
  // Business & Finance
  DollarSign,
  CreditCard,
  Receipt,
  ShoppingCart,
  Package,
  Truck,
  
  // Security
  Shield,
  ShieldCheck,
  ShieldAlert,
  Key,
  Fingerprint,
  
  // Development
  Code,
  Terminal,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  
  // Social
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Github,
  Youtube,
  
  // Miscellaneous
  HelpCircle,
  QuestionMarkCircle,
  AlertCircle,
  Bell,
  BellOff,
  Volume1,
  Volume2 as VolumeHigh,
  VolumeX as VolumeMute,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  RefreshCw,
  RefreshCcw,
  Repeat,
  Shuffle,
  SkipBack,
  SkipForward,
  FastForward,
  Rewind,
  PauseCircle,
  PlayCircle,
  StopCircle,
  Square as SquareIcon,
  Circle as CircleIcon,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  Heart as HeartIcon,
  Smile,
  Frown,
  Meh,
  Laugh,
  Angry,
  Surprised,
  Confused,
  Wink,
  Tongue,
  Kiss,
  Hug,
  ThumbsUp as ThumbUp,
  ThumbsDown as ThumbDown,
  Hand,
  Handshake,
  Peace,
  Victory,
  Clap,
  Wave,
  Point,
  Grab,
  Pinch,
  Pin,
  MapPin,
  Navigation,
  Compass,
  Globe,
  Map,
  MapPinned,
  Route,
  Signpost,
  Flag as FlagIcon,
  FlagTriangleLeft,
  FlagTriangleRight,
  FlagCheckered,
  FlagOff,
  FlagPole,
  FlagSwiss,
  FlagUk,
  FlagUs,
  FlagCa,
  FlagFr,
  FlagDe,
  FlagIt,
  FlagEs,
  FlagJp,
  FlagKr,
  FlagCn,
  FlagIn,
  FlagBr,
  FlagAu,
  FlagNz,
  FlagMx,
  FlagRu,
  FlagSa,
  FlagAe,
  FlagEg,
  FlagZa,
  FlagNg,
  FlagKe,
  FlagGh,
  FlagMa,
  FlagTz,
  FlagUg,
  FlagZw,
  FlagBw,
  FlagMz,
  FlagMw,
  FlagZm,
  FlagSn,
  FlagCi,
  FlagCm,
  FlagCd,
  FlagEt,
  FlagDz,
  FlagLy,
  FlagTn,
  FlagLr,
  FlagSl,
  FlagGn,
  FlagGw,
  FlagGm,
  FlagBf,
  FlagMl,
  FlagNe,
  FlagTd,
  FlagCf,
  FlagCg,
  FlagGa,
  FlagGq,
  FlagSt,
  FlagAo,
  FlagNa,
  FlagSz,
  FlagLs,
  FlagBi,
  FlagRw,
  FlagDj,
  FlagSo,
  FlagEr,
  FlagSs,
  FlagSd,
  FlagCm as Cameroon,
  FlagCd as Congo,
  FlagEt as Ethiopia,
  FlagDz as Algeria,
  FlagLy as Libya,
  FlagTn as Tunisia,
  FlagLr as Liberia,
  FlagSl as SierraLeone,
  FlagGn as Guinea,
  FlagGw as GuineaBissau,
  FlagGm as Gambia,
  FlagBf as BurkinaFaso,
  FlagMl as Mali,
  FlagNe as Niger,
  FlagTd as Chad,
  FlagCf as CentralAfricanRepublic,
  FlagCg as RepublicOfCongo,
  FlagGa as Gabon,
  FlagGq as EquatorialGuinea,
  FlagSt as SaoTomeAndPrincipe,
  FlagAo as Angola,
  FlagNa as Namibia,
  FlagSz as Eswatini,
  FlagLs as Lesotho,
  FlagBi as Burundi,
  FlagRw as Rwanda,
  FlagDj as Djibouti,
  FlagSo as Somalia,
  FlagEr as Eritrea,
  FlagSs as SouthSudan,
  FlagSd as Sudan
} from 'lucide-react'

// Create a lightweight icon registry for tree shaking
export const iconRegistry = {
  // Navigation
  home: Home,
  menu: Menu,
  x: X,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  
  // Actions
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash2,
  copy: Copy,
  download: Download,
  upload: Upload,
  save: Save,
  search: Search,
  filter: Filter,
  settings: Settings,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  
  // Status
  check: Check,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  loader: Loader2,
  
  // User & Auth
  user: User,
  users: Users,
  'user-plus': UserPlus,
  'log-out': LogOut,
  'log-in': LogIn,
  lock: Lock,
  unlock: Unlock,
  
  // Content
  'file-text': FileText,
  file: File,
  image: Image,
  video: Video,
  'book-open': BookOpen,
  book: Book,
  'message-square': MessageSquare,
  'message-circle': MessageCircle,
  mail: Mail,
  phone: Phone,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  
  // Media
  play: Play,
  pause: Pause,
  stop: Stop,
  volume: Volume2,
  'volume-x': VolumeX,
  mic: Mic,
  'mic-off': MicOff,
  camera: Camera,
  'camera-off': CameraOff,
  
  // Learning
  'graduation-cap': GraduationCap,
  award: Award,
  trophy: Trophy,
  star: Star,
  target: Target,
  zap: Zap,
  lightbulb: Lightbulb,
  brain: Brain,
  
  // Communication
  send: Send,
  reply: Reply,
  share: Share,
  link: Link,
  'external-link': ExternalLink,
  
  // Data & Analytics
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  activity: Activity,
  database: Database,
  
  // System
  wifi: Wifi,
  'wifi-off': WifiOff,
  battery: Battery,
  'battery-low': BatteryLow,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  
  // UI Elements
  eye: Eye,
  'eye-off': EyeOff,
  heart: Heart,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  tags: Tags,
  
  // Forms
  'check-square': CheckSquare,
  square: Square,
  circle: Circle,
  radio: Radio,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  
  // Navigation & Layout
  grid: Grid,
  list: List,
  layout: Layout,
  sidebar: Sidebar,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  
  // Tools
  wrench: Wrench,
  hammer: Hammer,
  scissors: Scissors,
  palette: Palette,
  brush: Brush,
  wand: Wand2,
  
  // Time & Date
  'calendar-days': CalendarDays,
  'calendar-check': CalendarCheck,
  'calendar-x': CalendarX,
  'clock-3': Clock3,
  'clock-4': Clock4,
  'clock-5': Clock5,
  'clock-6': Clock6,
  'clock-7': Clock7,
  'clock-8': Clock8,
  'clock-9': Clock9,
  'clock-10': Clock10,
  'clock-11': Clock11,
  'clock-12': Clock12,
  
  // Weather & Environment
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  'cloud-snow': CloudSnow,
  wind: Wind,
  
  // Business & Finance
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  receipt: Receipt,
  'shopping-cart': ShoppingCart,
  package: Package,
  truck: Truck,
  
  // Security
  shield: Shield,
  'shield-check': ShieldCheck,
  'shield-alert': ShieldAlert,
  key: Key,
  fingerprint: Fingerprint,
  
  // Development
  code: Code,
  terminal: Terminal,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  
  // Social
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  github: Github,
  youtube: Youtube,
  
  // Miscellaneous
  'help-circle': HelpCircle,
  'question-mark-circle': QuestionMarkCircle,
  'alert-circle': AlertCircle,
  bell: Bell,
  'bell-off': BellOff,
  'volume-1': Volume1,
  'volume-high': VolumeHigh,
  'volume-mute': VolumeMute,
  maximize: Maximize,
  minimize: Minimize,
  'rotate-ccw': RotateCcw,
  'rotate-cw': RotateCw,
  'refresh-cw': RefreshCw,
  'refresh-ccw': RefreshCcw,
  repeat: Repeat,
  shuffle: Shuffle,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'fast-forward': FastForward,
  rewind: Rewind,
  'pause-circle': PauseCircle,
  'play-circle': PlayCircle,
  'stop-circle': StopCircle,
  'square-icon': SquareIcon,
  'circle-icon': CircleIcon,
  triangle: Triangle,
  hexagon: Hexagon,
  octagon: Octagon,
  pentagon: Pentagon,
  diamond: Diamond,
  'heart-icon': HeartIcon,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  laugh: Laugh,
  angry: Angry,
  surprised: Surprised,
  confused: Confused,
  wink: Wink,
  tongue: Tongue,
  kiss: Kiss,
  hug: Hug,
  'thumb-up': ThumbUp,
  'thumb-down': ThumbDown,
  hand: Hand,
  handshake: Handshake,
  peace: Peace,
  victory: Victory,
  clap: Clap,
  wave: Wave,
  point: Point,
  grab: Grab,
  pinch: Pinch,
  pin: Pin,
  'map-pin': MapPin,
  navigation: Navigation,
  compass: Compass,
  globe: Globe,
  map: Map,
  'map-pinned': MapPinned,
  route: Route,
  signpost: Signpost,
  'flag-icon': FlagIcon,
  'flag-triangle-left': FlagTriangleLeft,
  'flag-triangle-right': FlagTriangleRight,
  'flag-checkered': FlagCheckered,
  'flag-off': FlagOff,
  'flag-pole': FlagPole,
  'flag-swiss': FlagSwiss,
  'flag-uk': FlagUk,
  'flag-us': FlagUs,
  'flag-ca': FlagCa,
  'flag-fr': FlagFr,
  'flag-de': FlagDe,
  'flag-it': FlagIt,
  'flag-es': FlagEs,
  'flag-jp': FlagJp,
  'flag-kr': FlagKr,
  'flag-cn': FlagCn,
  'flag-in': FlagIn,
  'flag-br': FlagBr,
  'flag-au': FlagAu,
  'flag-nz': FlagNz,
  'flag-mx': FlagMx,
  'flag-ru': FlagRu,
  'flag-sa': FlagSa,
  'flag-ae': FlagAe,
  'flag-eg': FlagEg,
  'flag-za': FlagZa,
  'flag-ng': FlagNg,
  'flag-ke': FlagKe,
  'flag-gh': FlagGh,
  'flag-ma': FlagMa,
  'flag-tz': FlagTz,
  'flag-ug': FlagUg,
  'flag-zw': FlagZw,
  'flag-bw': FlagBw,
  'flag-mz': FlagMz,
  'flag-mw': FlagMw,
  'flag-zm': FlagZm,
  'flag-sn': FlagSn,
  'flag-ci': FlagCi,
  'flag-cm': FlagCm,
  'flag-cd': FlagCd,
  'flag-et': FlagEt,
  'flag-dz': FlagDz,
  'flag-ly': FlagLy,
  'flag-tn': FlagTn,
  'flag-lr': FlagLr,
  'flag-sl': FlagSl,
  'flag-gn': FlagGn,
  'flag-gw': FlagGw,
  'flag-gm': FlagGm,
  'flag-bf': FlagBf,
  'flag-ml': FlagMl,
  'flag-ne': FlagNe,
  'flag-td': FlagTd,
  'flag-cf': FlagCf,
  'flag-cg': FlagCg,
  'flag-ga': FlagGa,
  'flag-gq': FlagGq,
  'flag-st': FlagSt,
  'flag-ao': FlagAo,
  'flag-na': FlagNa,
  'flag-sz': FlagSz,
  'flag-ls': FlagLs,
  'flag-bi': FlagBi,
  'flag-rw': FlagRw,
  'flag-dj': FlagDj,
  'flag-so': FlagSo,
  'flag-er': FlagEr,
  'flag-ss': FlagSs,
  'flag-sd': FlagSd,
  'cameroon': Cameroon,
  'congo': Congo,
  'ethiopia': Ethiopia,
  'algeria': Algeria,
  'libya': Libya,
  'tunisia': Tunisia,
  'liberia': Liberia,
  'sierra-leone': SierraLeone,
  'guinea': Guinea,
  'guinea-bissau': GuineaBissau,
  'gambia': Gambia,
  'burkina-faso': BurkinaFaso,
  'mali': Mali,
  'niger': Niger,
  'chad': Chad,
  'central-african-republic': CentralAfricanRepublic,
  'republic-of-congo': RepublicOfCongo,
  'gabon': Gabon,
  'equatorial-guinea': EquatorialGuinea,
  'sao-tome-and-principe': SaoTomeAndPrincipe,
  'angola': Angola,
  'namibia': Namibia,
  'eswatini': Eswatini,
  'lesotho': Lesotho,
  'burundi': Burundi,
  'rwanda': Rwanda,
  'djibouti': Djibouti,
  'somalia': Somalia,
  'eritrea': Eritrea,
  'south-sudan': SouthSudan,
  'sudan': Sudan
} as const

// Type for icon names
export type IconName = keyof typeof iconRegistry

// Helper function to get icon component
export const getIcon = (name: IconName) => {
  return iconRegistry[name]
}

// Helper function to check if icon exists
export const hasIcon = (name: string): name is IconName => {
  return name in iconRegistry
}
